package com.approvalflow.engine.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    REQUEST_CREATED,
    REQUEST_SUBMITTED,
    REQUEST_CANCELLED,
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    REQUEST_CHANGES_REQUESTED,
    STEP_APPROVED,
    STEP_REJECTED,
    STEP_ESCALATED,
    COMMENT_ADDED,
    DECISION_MADE
}
